name: Build iOS Flutter App

on:
  push:
    branches:
      - ios-test
      
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: parigo_ev_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: pod install
        working-directory: parigo_ev_app/ios

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Build Xcode archive
        run: |
          xcodebuild \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $RUNNER_TEMP/Runner.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO
        working-directory: parigo_ev_app/ios

      - name: Upload iOS archive
        uses: actions/upload-artifact@v4
        with:
          name: ios-archive
          path: ${{ runner.temp }}/Runner.xcarchive
